platform: linux
inputs:
- name: git-repo
outputs:
- name: artifact
run:
  dir: git-repo
  path: bash
  args:
  - -exc
  - |
    set -x     
    # format the version so that we can use lexicographic search to find the latest
    version=$(git describe | awk -F- '{printf "%s-%04d-%s", $1, $2, $3}')
    service=${cf_app_name_ex}
    test=${cf_app_name_ex}.Test
    filename=${service}-${version}.zip
    
    cd ..
    output_directory=${PWD}/artifact
    cd git-repo/${test}
    dotnet test -c release      

    cd ..
    cd ${service}
    dotnet publish -c release -o ./bin/release/netcoreapp/publish
    
    git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %aI %s" --no-merges > ./bin/release/netcoreapp/publish/gitlog.txt

    cd ..
    mkdir -p ${PWD}/${service}/bin/release/netcoreapp/publish/ci
    cp -r ${PWD}/ci/. ${PWD}/${service}/bin/release/netcoreapp/publish/ci
    
    mkdir -p ${PWD}/${service}/bin/release/netcoreapp/publish/results
    echo $version > ${PWD}/${service}/bin/release/netcoreapp/publish/results/version-tag.txt
    echo $version > ${PWD}/${service}/bin/release/netcoreapp/publish/version.txt
    
    tar -xvf ${PWD}/ci/docker/binfiles/newrelic-netcore20-agent_8.21.34.0_amd64.tar.gz -C ${PWD}/${service}/bin/release/netcoreapp/publish/
        
    cd ${PWD}/${service}/bin/release/netcoreapp/publish
    #zip -r ${output_directory}/${filename} ./* 
